version: '3.8'

services:
  only35-dictionary:
    container_name: only35-dictionary
    image: only35/dictionary:13.0
    build:
      context: .
      dockerfile: ./php-cli/Dockerfile
      args:
        - XDEBUG_HOST=${XDEBUG_HOST}
        - XDEBUG_PORT=${XDEBUG_PORT}
    working_dir: /app
    volumes:
      - ../:/app
    tty: true
    stdin_open: true
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
    name: carlonicora